Portfolio
Tushar151997/Portfolio-Setup_and_Mobile- pull request #1
Opened 2022-09-23 17:05 UTC by Tushar151997

2022-09-23 17:38 UTC, ichala requested changes
Hi @Tushar151997 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Redme✅ 
- Great Design✅ 
- Linters are passing ✅


 ## Required Changes ♻️

- [ ] **_🛑 Please Update your PR description & PR Title to be more descriptive, they should have a short summary describing introduced changes in more detail 🛑_** example:
- PR Title: Create navbar & header section
- PR Description : 
> - setup linters
> - create navbar
> - create a headline section
> - update readme 
> - etc


- [ ] _**check the comments below**_


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:38 UTC, ichala commented on index.html
> +                </div>
- [ ] for aesthetic reasons the images shouldn't be part of the content, kindly use  `CSS background-image` instead , you can read more about it [here](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image)

2022-09-23 17:38 UTC, ichala commented on index.html
> +            </div>
- [ ] Please note that this bar is not  part of the design and it shouldn't show up in your website , kindly remove it it only added on Figma to show you that the design is on mobile

![image](https://user-images.githubusercontent.com/89282221/192019861-188ff0df-97a3-44a7-b5da-42d4eeff236c.png)

2022-09-23 17:38 UTC, ichala commented on index.html
> +            </section>
- [ ] please add the missing border radius on the bottom left corner of the section to match Figma design

![image](https://user-images.githubusercontent.com/89282221/192023125-ef740ae2-415a-4ea1-a29f-b8a2893f06a0.png)

2022-09-23 17:38 UTC, ichala commented on index.html
> +            <section>
- [ ] all the content of the headline section should be aligned with flexbox, This gives us a lot of options to align all our elements, plus, it's responsive. so kindly fix it 🙏

2022-09-23 17:38 UTC, ichala commented on index.html
> +            </section>
- [ ] Please note that the background color of the navbar & the headline section should be both white (`#ffffff`) and not `#f7f7f9` only the body of the website is using that color , kindly fix that

2022-09-24 17:56 UTC, ichala requested changes
Hi @Tushar151997 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Pr description ✅ 
- Good Design ✅
- Linters are passing ✅


 ## Required Changes ♻️

- [ ] **_Check the comments below_**



## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 17:56 UTC, ichala commented on index.html
> +    </nav>
- [ ] please not that after the changes you made I cannot see that navbar button anymore , kindly fix that 

![image](https://user-images.githubusercontent.com/89282221/192111819-f24fc694-30c6-4c26-b324-da6f80fc989a.png)

2022-09-24 17:56 UTC, ichala commented on style.css
> +}
- [ ] as in the previous review please add the border-radius in the bottom left side of the headline section

**_Hint : you can add `border-bottom-left-radius: 50px;` to your section styling_**



![image](https://user-images.githubusercontent.com/89282221/192023125-ef740ae2-415a-4ea1-a29f-b8a2893f06a0.png)

2022-09-24 20:13 UTC, fobadara requested changes
Hi @Tushar151997, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
✅ Linters are passing

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 20:13 UTC, fobadara commented on index.html
> +    </section>
[REQUIRED] Due to some changes you now have two spaces on the left and right.

Your Design

![image](https://user-images.githubusercontent.com/62938735/192116405-5bf180e4-aab6-4119-92a8-881091c1f488.png)

2022-09-24 20:25 UTC, Tushar151997 commented
Thank you for the review please check I have made the required changes @fobadara

2022-09-24 20:50 UTC, franclobo approved these changes
Hi @Tushar151997, 

# STATUS: APPROVED 😃 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 

## Optional suggestions
- [ ] **[OPTIONAL]** Kindly make sure that all the links in the README file work as expected. To fix the MIT link please 🙏🏽 add the MIT LICENSE file to your repository for a professional README file.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 20:56 UTC, merged